#!/bin/bash

DIALOG=${DIALOG=gdialog}

clearVars() {
 unset $@
}

gracefulExit() {
 clearVars
 exit 0
}

usage() {
 green "Usage: " `cyan "question <QuotedText>"`
}

trap "gracefulExit" INT PWR QUIT TERM

if [[ $# -gt 1 ]];
then
    red "Error: " `white "Too many arguments"`
    usage
    gracefulExit
elif [[ $# -lt 1 ]] || [[ $1 == $str ]];
then
    red "Error: " `white "Missing argument"`
    usage
    gracefulExit
else
    $DIALOG --title "Question" --yesno "${1}" 10 11 --clear
    case $? in
     0) echo "yes">ans.txt;;

     1) echo "no">ans.txt;;
    esac
    gracefulExit
fi


