#!/bin/bash

clear_vars() {
 unset NUM
}

greaceful_exit() {
 clear_vars
 exit 0;
}

error_exit() {
 red "\n\tError: " `white " Missing Parameter\n"`
 usage
 exit 121
}

usage() {
 green "\tUsage: " `cyan "toHex <integer>"`
}

trap "graceful_exit" INT TERM QUIT PWR

if [[ $# -gt 1 ]];
then
   for NUM in $@
   do
     magenta $(echo "obase=16; $NUM" | bc)"\n"
   done
else
   case $# in
    0)
     error_exit
     ;;

   1)
    magenta $(echo "obase=16; $1" | bc)"\n"
    ;;
   esac
fi
