#!/bin/bash

DIALOG=${DIALOG=gdialog}

clearVars() {
 unset $@ lines LINE
}

removeTemp() {
    rm ans.txt
}

gracefulExit() {
    clearVars
    exit 0
}

safeExit() {
    rm ans.txt
    gracefulExit
}

usage() {
 green "Usage: " `white "choice"`
 gracefulExit
}

readFile() {
    clear
    white "Thanks for your input!"
    for LINE in `cat ans.txt`
    do 
        lines="${lines}$LINE "
    done
    
    if [[ ${lines} == "current time " ]];
    then
        white "Getting the current time"
        nterminal "clock"

    elif [[ ${lines} == "clean logs " ]];
    then
        white "Cleaning logs"
        exec 3>&1
        result=$($DIALOG --title "Rotate log files" \
        --aspect 340 320 --checklist "Choose which logs to rotate" 100 40 3 \
            1 "messages" off \
            2 "boot" off \
            3 "syslog" off \
            4 "deez nuts" 2>&1 1>&3)
        
        if [[ $result =~ [\|] ]];
        then
            _result="${result//|/ }"
            for L in $_result
            do
                if [[ $L -eq 1 ]];
                then
                    newArray+=("messages")
                elif [[ $L -eq 2 ]];
                then
                    newArray+=("boot");
                elif [[ $L -eq 3 ]];
                then
                    newArray+=("syslog")
                elif [[ $L -eq 4 ]];
                then
                    newArray+=("deez_nuts")
                fi
            done
            for element in ${newArray[@]};do
                white "Rotating ${element}"
            done;
        elif [[ ! $result =~ [\|] ]];
        then
            case $result in
                1)
                    white "Rotating messages";;

                2)
                    white "Rotating boot";;

                3)
                    white "Rotating syslog";;

                4)
                    white "Rotating deez nuts";;
            esac
        fi
        # nterminal "sudo ~/bin/cleaner"
        return

    elif [[ ${lines} == "mount shared drive " ]];
    then
        white "Mounting shared drive"
        nterminal 'white "Mounting shared drive"'
    elif [[ ${lines} == "view shared drives " ]];
    then
        white "Viewing shared drives"
        nterminal 'white "Viewing shared drives"'
    fi
    removeFile
}

removeFile() {
    rm ans.txt
}

start() {
    $DIALOG  --backtitle "Utilities Selection" \
    --title "Utilities Command Selection" \
    --aspect 444 422 \
    --clear \
    --radiolist "Select a utility to execute:" 90 90 2>ans.txt \
        1 "current time" off \
        2 "clean logs" off \
        3 "mount shared drive" off \
        4 "view shared drives" off

    case $? in
     0) readFile;;

     1) removeFile;;
    esac
    gracefulExit
}

trap "safeExit" INT PWR QUIT TERM

if [[ $# -gt 0 ]];
then
    red "Error: " `white "Too many arguments"`
    usage   
else
    start
fi