#!/bin/bash

DIALOG=${DIALOG=gdialog}

clearVars() {
 unset $@ lines LINE
}

removeTemp() {
    rm ans.txt
}

gracefulExit() {
    clearVars
    exit 0
}

safeExit() {
    rm ans.txt
    gracefulExit
}

usage() {
 green "Usage: " `white "choice"`
 gracefulExit
}

readFile() {
    clear
    white "Thanks for your input!"
    for LINE in `cat ans.txt`
    do 
        lines="${lines}$LINE "
    done
    
    if [[ ${lines} == "current time " ]];
    then
        printf "\n\tGetting the current time\n\n"
        nterminal "clock"

    elif [[ ${lines} == "clean logs " ]];
    then
        printf "\n\tCleaning logs\n\n"
        exec 3>&1
        result=$($DIALOG --title "Rotate log files" --checklist "Choose which logs to rotate" 100 40 3 \
            1 "messages" off \
            2 "boot" off \
            3 "syslog" off \
            4 "deez nuts" 2>&1 1>&3)
        
        if [[ $result =~ [\|] ]]
        then
            _result="${result//|/ }"
            # echo ${_result[0]}

            for L in $_result
            do
                newArray+=($L)
            done

            printf "\n\n\t\tArray Length: ${#newArray[@]}\n\n\n\n"

            # printf "\n\t$_result\n\n\n\n"
        fi
        # nterminal "sudo ~/bin/cleaner"
        return

    elif [[ ${lines} == "mount shared drive " ]];
    then
        printf "\n\tMounting shared drive\n\n"
        nterminal "sudo mountshare"
    else
        printf "\n\tViewing shared drives\n\n"
        nterminal "sudo viewshares"
    fi
    removeFile
}

removeFile() {
    rm ans.txt
}

start() {
    $DIALOG  --backtitle "Utilities Selection" \
    --title "Utilities Command Selection" \
    --clear \
    --radiolist "Select a utility to execute:" 90 90 2>ans.txt \
        1 "current time" off \
        2 "clean logs" off \
        3 "mount shared drive" off \
        4 "view shared drives" off

    case $? in
     0) readFile;;

     1) removeFile;;
    esac
    gracefulExit
}

trap "safeExit" INT PWR QUIT TERM

if [[ $# -gt 0 ]];
then
    red "Error: " `white "Too many arguments"`
    usage   
else
    start
fi